cmd_output:
  message_type: romea_mobile_base_msgs/SkidSteeringCommand
  message_priority: 100
cmd_range:
  maximal_linear_speed:
    slow_mode: 0.75
    turbo_mode: 1.5
  maximal_angular_speed:
    slow_mode: 0.7
    turbo_mode: 1.6
